services:
  redis:
    image: redis:8.4
    ports:
    - '6379:6379'
  temporal:
    image: temporalio/admin-tools:1.29
    container_name: temporal-server
    entrypoint: ["temporal", "server", "start-dev", "--ip", "0.0.0.0"]
    ports:
    - "7233:7233"
    - "8233:8233"
